#resources:
 # - name: gitResource
 #   type: GitRepo
 #   configuration:
 #     gitProvider: git_v
 #     path: vishnurao12/pipelines
pipelines:
  - name: pipelines_test
    steps:
      - name: myStep1
        type: Bash
        #configuration: 
   #       inputResources: # optional
    #        - name: gitResource
          #inputSteps: 
            #- name: myStep1
         # runtime:
          #  type: image
           # image:
            #  auto:
             #   language: java
              #  versions:
               #   - 11
        execution:
          onExecute:
            - printenv
            - cat /var/lib/docker/image/aufs/repositories.json
     # - name: myStep2
      #  type: Bash
       # configuration: 
       #   inputResources: # optional
       #     - name: gitResource
          #inputSteps: 
           # - name: myStep1
       # execution:
        #  onExecute:
        #    - printenv
     # - name: myStep3
     #   type: Bash
     #   configuration: 
     #     inputResources: # optional
     #       - name: gitResource
        #  inputSteps: 
         #   - name: myStep2
     #   execution:
      #   onExecute:
       #     - printenv



      
